name: Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip pip-tools

    - name: Update requirements
      run: |
        # Generate updated requirements if requirements.in exists
        if [ -f requirements.in ]; then
          pip-compile --upgrade requirements.in
        fi
        
        # Update development requirements if they exist
        if [ -f requirements-dev.in ]; then
          pip-compile --upgrade requirements-dev.in
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: update dependencies"
        body: |
          Automated dependency update
          
          - Updated Python package dependencies
          - Generated by GitHub Actions workflow
          
          Please review the changes and ensure all tests pass before merging.
        branch: update-dependencies
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety pip-audit

    - name: Run safety audit
      run: |
        safety check --json --output safety-audit.json
      continue-on-error: true

    - name: Run pip-audit
      run: |
        pip-audit --format=json --output=pip-audit.json
      continue-on-error: true

    - name: Upload audit reports
      uses: actions/upload-artifact@v3
      with:
        name: security-audit-reports
        path: |
          safety-audit.json
          pip-audit.json
